#############################################################
#                                                           #
# generated by teltyp_gen_perl.pl                           #
# Tue Sep  7 14:56:36 2010                                  #
# KEQ hinzugefuegt 31.03.11                                 #
#############################################################

package TELTYP_KR1;

# use strict;



#############################################################
#  Telegramm RPR                                            #
#############################################################

sub RPR_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "RPR";
   ${$rtel}{'path_filename'} = substr(${$rbuf},4,100);
}


sub RPR_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "RPR";
   ${$rtel}{'path_filename'} = substr(${$rbuf},3,100);
}


sub RPR_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "RPR";
   ${$rtel}{'path_filename'} = $f[1];
}


sub RPR_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "RPR";
   ${$rbuf} .= sprintf(" %-100.100s",${$rtel}{'path_filename'});
}


sub RPR_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "RPR";
   ${$rbuf} .= sprintf("%-100.100s",${$rtel}{'path_filename'});
}


sub RPR_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "RPR";
   ${$rbuf} .= sprintf("\t%-.100s",${$rtel}{'path_filename'});
}


sub RPR_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm RPR: ";
   $trcbuf .= "path_filename='" . substr(${$rbuf},4,100) . "'";

   return $trcbuf;
}


sub RPR_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm RPR: ";
   $trcbuf .= "path_filename='" . substr(${$rbuf},3,100) . "'";

   return $trcbuf;
}


sub RPR_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm RPR: ";
   $trcbuf .= "path_filename='" . $f[1]  . "'";

   return $trcbuf;
}


sub RPR_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm RPR: ";
   $trcbuf .= "path_filename='" . ${$rtel}{"path_filename"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm KEA                                            #
#############################################################

sub KEA_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KEA";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},4,12);
}


sub KEA_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KEA";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},3,12);
}


sub KEA_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KEA";
   ${$rtel}{'wannen_id_12'} = $f[1];
}


sub KEA_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEA";
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'wannen_id_12'});
}


sub KEA_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEA";
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'wannen_id_12'});
}


sub KEA_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEA";
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'wannen_id_12'});
}


sub KEA_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEA: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},4,12) . "'";

   return $trcbuf;
}


sub KEA_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEA: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},3,12) . "'";

   return $trcbuf;
}


sub KEA_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KEA: ";
   $trcbuf .= "wannen_id_12='" . $f[1]  . "'";

   return $trcbuf;
}


sub KEA_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEA: ";
   $trcbuf .= "wannen_id_12='" . ${$rtel}{"wannen_id_12"} . "'";

   return $trcbuf;
}


#############################################################
#  Telegramm KEQ                                            #
#############################################################

sub KEQ_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KEQ";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},4,12);
}


sub KEQ_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KEQ";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},3,12);
}


sub KEQ_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KEQ";
   ${$rtel}{'wannen_id_12'} = $f[1];
}


sub KEQ_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEQ";
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'wannen_id_12'});
}


sub KEQ_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEQ";
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'wannen_id_12'});
}


sub KEQ_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEQ";
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'wannen_id_12'});
}


sub KEQ_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEQ: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},4,12) . "'";

   return $trcbuf;
}


sub KEQ_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEQ: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},3,12) . "'";

   return $trcbuf;
}


sub KEQ_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KEQ: ";
   $trcbuf .= "wannen_id_12='" . $f[1]  . "'";

   return $trcbuf;
}


sub KEQ_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEQ: ";
   $trcbuf .= "wannen_id_12='" . ${$rtel}{"wannen_id_12"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm KED                                            #
#############################################################

sub KED_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KED";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},4,12);
   ${$rtel}{'artnr'} = substr(${$rbuf},17,14);
   ${$rtel}{'grs'} = sprintf("%d",substr(${$rbuf},32,3));
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},36,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},43,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},45,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},47,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},55,6));
   ${$rtel}{'bezeichnung'} = substr(${$rbuf},62,18);
   ${$rtel}{'farbe'} = substr(${$rbuf},81,12);
   ${$rtel}{'laenge'} = sprintf("%d",substr(${$rbuf},94,6));
   ${$rtel}{'breite'} = sprintf("%d",substr(${$rbuf},101,6));
   ${$rtel}{'hoehe'} = sprintf("%d",substr(${$rbuf},108,6));
   ${$rtel}{'volumen'} = sprintf("%d",substr(${$rbuf},115,6));
   ${$rtel}{'gewicht'} = sprintf("%d",substr(${$rbuf},122,6));
   ${$rtel}{'upi'} = substr(${$rbuf},129,50);
   ${$rtel}{'ean1'} = substr(${$rbuf},180,13);
   ${$rtel}{'ean2'} = substr(${$rbuf},194,13);
   ${$rtel}{'ean3'} = substr(${$rbuf},208,13);
   ${$rtel}{'ean4'} = substr(${$rbuf},222,13);
   ${$rtel}{'ean5'} = substr(${$rbuf},236,13);
   ${$rtel}{'ean6'} = substr(${$rbuf},250,13);
}


sub KED_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KED";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},3,12);
   ${$rtel}{'artnr'} = substr(${$rbuf},15,14);
   ${$rtel}{'grs'} = sprintf("%d",substr(${$rbuf},29,3));
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},32,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},38,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},39,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},40,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},47,6));
   ${$rtel}{'bezeichnung'} = substr(${$rbuf},53,18);
   ${$rtel}{'farbe'} = substr(${$rbuf},71,12);
   ${$rtel}{'laenge'} = sprintf("%d",substr(${$rbuf},83,6));
   ${$rtel}{'breite'} = sprintf("%d",substr(${$rbuf},89,6));
   ${$rtel}{'hoehe'} = sprintf("%d",substr(${$rbuf},95,6));
   ${$rtel}{'volumen'} = sprintf("%d",substr(${$rbuf},101,6));
   ${$rtel}{'gewicht'} = sprintf("%d",substr(${$rbuf},107,6));
   ${$rtel}{'upi'} = substr(${$rbuf},113,50);
   ${$rtel}{'ean1'} = substr(${$rbuf},163,13);
   ${$rtel}{'ean2'} = substr(${$rbuf},176,13);
   ${$rtel}{'ean3'} = substr(${$rbuf},189,13);
   ${$rtel}{'ean4'} = substr(${$rbuf},202,13);
   ${$rtel}{'ean5'} = substr(${$rbuf},215,13);
   ${$rtel}{'ean6'} = substr(${$rbuf},228,13);
}


sub KED_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KED";
   ${$rtel}{'wannen_id_12'} = $f[1];
   ${$rtel}{'artnr'} = $f[2];
   ${$rtel}{'grs'} = sprintf("%d",$f[3]);
   ${$rtel}{'lkz'} = sprintf("%d",$f[4]);
   ${$rtel}{'zoll_kz'} = $f[5];
   ${$rtel}{'sperr_kz'} = $f[6];
   ${$rtel}{'we_sendung'} = sprintf("%d",$f[7]);
   ${$rtel}{'wap'} = sprintf("%d",$f[8]);
   ${$rtel}{'bezeichnung'} = $f[9];
   ${$rtel}{'farbe'} = $f[10];
   ${$rtel}{'laenge'} = sprintf("%d",$f[11]);
   ${$rtel}{'breite'} = sprintf("%d",$f[12]);
   ${$rtel}{'hoehe'} = sprintf("%d",$f[13]);
   ${$rtel}{'volumen'} = sprintf("%d",$f[14]);
   ${$rtel}{'gewicht'} = sprintf("%d",$f[15]);
   ${$rtel}{'upi'} = $f[16];
   ${$rtel}{'ean1'} = $f[17];
   ${$rtel}{'ean2'} = $f[18];
   ${$rtel}{'ean3'} = $f[19];
   ${$rtel}{'ean4'} = $f[20];
   ${$rtel}{'ean5'} = $f[21];
   ${$rtel}{'ean6'} = $f[22];
}


sub KED_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KED";
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf(" %-14.14s",${$rtel}{'artnr'});
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'grs'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf(" %07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf(" %-18.18s",${$rtel}{'bezeichnung'});
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'farbe'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'laenge'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'breite'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'hoehe'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'volumen'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'gewicht'});
   ${$rbuf} .= sprintf(" %-50.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf(" %-13.13s",${$rtel}{'ean1'});
   ${$rbuf} .= sprintf(" %-13.13s",${$rtel}{'ean2'});
   ${$rbuf} .= sprintf(" %-13.13s",${$rtel}{'ean3'});
   ${$rbuf} .= sprintf(" %-13.13s",${$rtel}{'ean4'});
   ${$rbuf} .= sprintf(" %-13.13s",${$rtel}{'ean5'});
   ${$rbuf} .= sprintf(" %-13.13s",${$rtel}{'ean6'});
}


sub KED_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KED";
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("%-14.14s",${$rtel}{'artnr'});
   ${$rbuf} .= sprintf("%03d",${$rtel}{'grs'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("%07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("%-18.18s",${$rtel}{'bezeichnung'});
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'farbe'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'laenge'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'breite'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'hoehe'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'volumen'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'gewicht'});
   ${$rbuf} .= sprintf("%-50.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf("%-13.13s",${$rtel}{'ean1'});
   ${$rbuf} .= sprintf("%-13.13s",${$rtel}{'ean2'});
   ${$rbuf} .= sprintf("%-13.13s",${$rtel}{'ean3'});
   ${$rbuf} .= sprintf("%-13.13s",${$rtel}{'ean4'});
   ${$rbuf} .= sprintf("%-13.13s",${$rtel}{'ean5'});
   ${$rbuf} .= sprintf("%-13.13s",${$rtel}{'ean6'});
}


sub KED_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KED";
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("\t%-.14s",${$rtel}{'artnr'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'grs'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("\t%-.18s",${$rtel}{'bezeichnung'});
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'farbe'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'laenge'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'breite'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'hoehe'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'volumen'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'gewicht'});
   ${$rbuf} .= sprintf("\t%-.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf("\t%-.13s",${$rtel}{'ean1'});
   ${$rbuf} .= sprintf("\t%-.13s",${$rtel}{'ean2'});
   ${$rbuf} .= sprintf("\t%-.13s",${$rtel}{'ean3'});
   ${$rbuf} .= sprintf("\t%-.13s",${$rtel}{'ean4'});
   ${$rbuf} .= sprintf("\t%-.13s",${$rtel}{'ean5'});
   ${$rbuf} .= sprintf("\t%-.13s",${$rtel}{'ean6'});
}


sub KED_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KED: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},4,12) . "', ";
   $trcbuf .= "artnr='" . substr(${$rbuf},17,14) . "', ";
   $trcbuf .= "grs=" . sprintf("%d",substr(${$rbuf},32,3)) . ", ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},36,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},43,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},45,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},47,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},55,6)) . ", ";
   $trcbuf .= "bezeichnung='" . substr(${$rbuf},62,18) . "', ";
   $trcbuf .= "farbe='" . substr(${$rbuf},81,12) . "', ";
   $trcbuf .= "laenge=" . sprintf("%d",substr(${$rbuf},94,6)) . ", ";
   $trcbuf .= "breite=" . sprintf("%d",substr(${$rbuf},101,6)) . ", ";
   $trcbuf .= "hoehe=" . sprintf("%d",substr(${$rbuf},108,6)) . ", ";
   $trcbuf .= "volumen=" . sprintf("%d",substr(${$rbuf},115,6)) . ", ";
   $trcbuf .= "gewicht=" . sprintf("%d",substr(${$rbuf},122,6)) . ", ";
   $trcbuf .= "upi='" . substr(${$rbuf},129,50) . "', ";
   $trcbuf .= "ean1='" . substr(${$rbuf},180,13) . "', ";
   $trcbuf .= "ean2='" . substr(${$rbuf},194,13) . "', ";
   $trcbuf .= "ean3='" . substr(${$rbuf},208,13) . "', ";
   $trcbuf .= "ean4='" . substr(${$rbuf},222,13) . "', ";
   $trcbuf .= "ean5='" . substr(${$rbuf},236,13) . "', ";
   $trcbuf .= "ean6='" . substr(${$rbuf},250,13) . "'";

   return $trcbuf;
}


sub KED_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KED: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},3,12) . "', ";
   $trcbuf .= "artnr='" . substr(${$rbuf},15,14) . "', ";
   $trcbuf .= "grs=" . sprintf("%d",substr(${$rbuf},29,3)) . ", ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},32,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},38,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},39,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},40,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},47,6)) . ", ";
   $trcbuf .= "bezeichnung='" . substr(${$rbuf},53,18) . "', ";
   $trcbuf .= "farbe='" . substr(${$rbuf},71,12) . "', ";
   $trcbuf .= "laenge=" . sprintf("%d",substr(${$rbuf},83,6)) . ", ";
   $trcbuf .= "breite=" . sprintf("%d",substr(${$rbuf},89,6)) . ", ";
   $trcbuf .= "hoehe=" . sprintf("%d",substr(${$rbuf},95,6)) . ", ";
   $trcbuf .= "volumen=" . sprintf("%d",substr(${$rbuf},101,6)) . ", ";
   $trcbuf .= "gewicht=" . sprintf("%d",substr(${$rbuf},107,6)) . ", ";
   $trcbuf .= "upi='" . substr(${$rbuf},113,50) . "', ";
   $trcbuf .= "ean1='" . substr(${$rbuf},163,13) . "', ";
   $trcbuf .= "ean2='" . substr(${$rbuf},176,13) . "', ";
   $trcbuf .= "ean3='" . substr(${$rbuf},189,13) . "', ";
   $trcbuf .= "ean4='" . substr(${$rbuf},202,13) . "', ";
   $trcbuf .= "ean5='" . substr(${$rbuf},215,13) . "', ";
   $trcbuf .= "ean6='" . substr(${$rbuf},228,13) . "'";

   return $trcbuf;
}


sub KED_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KED: ";
   $trcbuf .= "wannen_id_12='" . $f[1]  . "', ";
   $trcbuf .= "artnr='" . $f[2]  . "', ";
   $trcbuf .= "grs=" . $f[3]  . ", ";
   $trcbuf .= "lkz=" . $f[4]  . ", ";
   $trcbuf .= "zoll_kz='" . $f[5]  . "', ";
   $trcbuf .= "sperr_kz='" . $f[6]  . "', ";
   $trcbuf .= "we_sendung=" . $f[7]  . ", ";
   $trcbuf .= "wap=" . $f[8]  . ", ";
   $trcbuf .= "bezeichnung='" . $f[9]  . "', ";
   $trcbuf .= "farbe='" . $f[10]  . "', ";
   $trcbuf .= "laenge=" . $f[11]  . ", ";
   $trcbuf .= "breite=" . $f[12]  . ", ";
   $trcbuf .= "hoehe=" . $f[13]  . ", ";
   $trcbuf .= "volumen=" . $f[14]  . ", ";
   $trcbuf .= "gewicht=" . $f[15]  . ", ";
   $trcbuf .= "upi='" . $f[16]  . "', ";
   $trcbuf .= "ean1='" . $f[17]  . "', ";
   $trcbuf .= "ean2='" . $f[18]  . "', ";
   $trcbuf .= "ean3='" . $f[19]  . "', ";
   $trcbuf .= "ean4='" . $f[20]  . "', ";
   $trcbuf .= "ean5='" . $f[21]  . "', ";
   $trcbuf .= "ean6='" . $f[22]  . "'";

   return $trcbuf;
}


sub KED_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KED: ";
   $trcbuf .= "wannen_id_12='" . ${$rtel}{"wannen_id_12"} . "', ";
   $trcbuf .= "artnr='" . ${$rtel}{"artnr"} . "', ";
   $trcbuf .= "grs=" . ${$rtel}{"grs"} . ", ";
   $trcbuf .= "lkz=" . ${$rtel}{"lkz"} . ", ";
   $trcbuf .= "zoll_kz='" . ${$rtel}{"zoll_kz"} . "', ";
   $trcbuf .= "sperr_kz='" . ${$rtel}{"sperr_kz"} . "', ";
   $trcbuf .= "we_sendung=" . ${$rtel}{"we_sendung"} . ", ";
   $trcbuf .= "wap=" . ${$rtel}{"wap"} . ", ";
   $trcbuf .= "bezeichnung='" . ${$rtel}{"bezeichnung"} . "', ";
   $trcbuf .= "farbe='" . ${$rtel}{"farbe"} . "', ";
   $trcbuf .= "laenge=" . ${$rtel}{"laenge"} . ", ";
   $trcbuf .= "breite=" . ${$rtel}{"breite"} . ", ";
   $trcbuf .= "hoehe=" . ${$rtel}{"hoehe"} . ", ";
   $trcbuf .= "volumen=" . ${$rtel}{"volumen"} . ", ";
   $trcbuf .= "gewicht=" . ${$rtel}{"gewicht"} . ", ";
   $trcbuf .= "upi='" . ${$rtel}{"upi"} . "', ";
   $trcbuf .= "ean1='" . ${$rtel}{"ean1"} . "', ";
   $trcbuf .= "ean2='" . ${$rtel}{"ean2"} . "', ";
   $trcbuf .= "ean3='" . ${$rtel}{"ean3"} . "', ";
   $trcbuf .= "ean4='" . ${$rtel}{"ean4"} . "', ";
   $trcbuf .= "ean5='" . ${$rtel}{"ean5"} . "', ";
   $trcbuf .= "ean6='" . ${$rtel}{"ean6"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm KEE                                            #
#############################################################

sub KEE_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KEE";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},4,12);
   ${$rtel}{'status'} = substr(${$rbuf},17,1);
}


sub KEE_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KEE";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},3,12);
   ${$rtel}{'status'} = substr(${$rbuf},15,1);
}


sub KEE_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KEE";
   ${$rtel}{'wannen_id_12'} = $f[1];
   ${$rtel}{'status'} = $f[2];
}


sub KEE_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEE";
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'status'});
}


sub KEE_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEE";
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'status'});
}


sub KEE_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KEE";
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'status'});
}


sub KEE_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEE: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},4,12) . "', ";
   $trcbuf .= "status='" . substr(${$rbuf},17,1) . "'";

   return $trcbuf;
}


sub KEE_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEE: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},3,12) . "', ";
   $trcbuf .= "status='" . substr(${$rbuf},15,1) . "'";

   return $trcbuf;
}


sub KEE_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KEE: ";
   $trcbuf .= "wannen_id_12='" . $f[1]  . "', ";
   $trcbuf .= "status='" . $f[2]  . "'";

   return $trcbuf;
}


sub KEE_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KEE: ";
   $trcbuf .= "wannen_id_12='" . ${$rtel}{"wannen_id_12"} . "', ";
   $trcbuf .= "status='" . ${$rtel}{"status"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm KAD                                            #
#############################################################

sub KAD_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KAD";
   ${$rtel}{'auft_typ_kr'} = substr(${$rbuf},4,4);
   ${$rtel}{'auftr_typ_arl'} = substr(${$rbuf},9,1);
   ${$rtel}{'subtyp'} = sprintf("%d",substr(${$rbuf},11,2));
   ${$rtel}{'auft_seq'} = sprintf("%d",substr(${$rbuf},14,6));
   ${$rtel}{'tag'} = sprintf("%d",substr(${$rbuf},21,3));
   ${$rtel}{'lv'} = sprintf("%d",substr(${$rbuf},25,1));
   ${$rtel}{'batch'} = sprintf("%d",substr(${$rbuf},27,2));
   ${$rtel}{'subbatch'} = sprintf("%d",substr(${$rbuf},30,1));
   ${$rtel}{'sdg_im_batch'} = sprintf("%d",substr(${$rbuf},32,4));
   ${$rtel}{'artikelzaehler'} = sprintf("%d",substr(${$rbuf},37,2));
   ${$rtel}{'bs_flag'} = substr(${$rbuf},40,1);
   ${$rtel}{'artikelnr'} = substr(${$rbuf},42,14);
   ${$rtel}{'artikelgrs'} = substr(${$rbuf},57,3);
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},61,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},68,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},70,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},72,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},80,6));
   ${$rtel}{'bezeichnung'} = substr(${$rbuf},87,18);
   ${$rtel}{'farbe'} = substr(${$rbuf},106,12);
   ${$rtel}{'upi'} = substr(${$rbuf},119,50);
   ${$rtel}{'layout_nr'} = sprintf("%d",substr(${$rbuf},170,2));
}


sub KAD_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KAD";
   ${$rtel}{'auft_typ_kr'} = substr(${$rbuf},3,4);
   ${$rtel}{'auftr_typ_arl'} = substr(${$rbuf},7,1);
   ${$rtel}{'subtyp'} = sprintf("%d",substr(${$rbuf},8,2));
   ${$rtel}{'auft_seq'} = sprintf("%d",substr(${$rbuf},10,6));
   ${$rtel}{'tag'} = sprintf("%d",substr(${$rbuf},16,3));
   ${$rtel}{'lv'} = sprintf("%d",substr(${$rbuf},19,1));
   ${$rtel}{'batch'} = sprintf("%d",substr(${$rbuf},20,2));
   ${$rtel}{'subbatch'} = sprintf("%d",substr(${$rbuf},22,1));
   ${$rtel}{'sdg_im_batch'} = sprintf("%d",substr(${$rbuf},23,4));
   ${$rtel}{'artikelzaehler'} = sprintf("%d",substr(${$rbuf},27,2));
   ${$rtel}{'bs_flag'} = substr(${$rbuf},29,1);
   ${$rtel}{'artikelnr'} = substr(${$rbuf},30,14);
   ${$rtel}{'artikelgrs'} = substr(${$rbuf},44,3);
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},47,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},53,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},54,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},55,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},62,6));
   ${$rtel}{'bezeichnung'} = substr(${$rbuf},68,18);
   ${$rtel}{'farbe'} = substr(${$rbuf},86,12);
   ${$rtel}{'upi'} = substr(${$rbuf},98,50);
   ${$rtel}{'layout_nr'} = sprintf("%d",substr(${$rbuf},148,2));
}


sub KAD_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KAD";
   ${$rtel}{'auft_typ_kr'} = $f[1];
   ${$rtel}{'auftr_typ_arl'} = $f[2];
   ${$rtel}{'subtyp'} = sprintf("%d",$f[3]);
   ${$rtel}{'auft_seq'} = sprintf("%d",$f[4]);
   ${$rtel}{'tag'} = sprintf("%d",$f[5]);
   ${$rtel}{'lv'} = sprintf("%d",$f[6]);
   ${$rtel}{'batch'} = sprintf("%d",$f[7]);
   ${$rtel}{'subbatch'} = sprintf("%d",$f[8]);
   ${$rtel}{'sdg_im_batch'} = sprintf("%d",$f[9]);
   ${$rtel}{'artikelzaehler'} = sprintf("%d",$f[10]);
   ${$rtel}{'bs_flag'} = $f[11];
   ${$rtel}{'artikelnr'} = $f[12];
   ${$rtel}{'artikelgrs'} = $f[13];
   ${$rtel}{'lkz'} = sprintf("%d",$f[14]);
   ${$rtel}{'zoll_kz'} = $f[15];
   ${$rtel}{'sperr_kz'} = $f[16];
   ${$rtel}{'we_sendung'} = sprintf("%d",$f[17]);
   ${$rtel}{'wap'} = sprintf("%d",$f[18]);
   ${$rtel}{'bezeichnung'} = $f[19];
   ${$rtel}{'farbe'} = $f[20];
   ${$rtel}{'upi'} = $f[21];
   ${$rtel}{'layout_nr'} = sprintf("%d",$f[22]);
}


sub KAD_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KAD";
   ${$rbuf} .= sprintf(" %-4.4s",${$rtel}{'auft_typ_kr'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'auftr_typ_arl'});
   ${$rbuf} .= sprintf(" %02d",${$rtel}{'subtyp'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'auft_seq'});
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'tag'});
   ${$rbuf} .= sprintf(" %01d",${$rtel}{'lv'});
   ${$rbuf} .= sprintf(" %02d",${$rtel}{'batch'});
   ${$rbuf} .= sprintf(" %01d",${$rtel}{'subbatch'});
   ${$rbuf} .= sprintf(" %04d",${$rtel}{'sdg_im_batch'});
   ${$rbuf} .= sprintf(" %02d",${$rtel}{'artikelzaehler'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'bs_flag'});
   ${$rbuf} .= sprintf(" %-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf(" %-3.3s",${$rtel}{'artikelgrs'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf(" %07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf(" %-18.18s",${$rtel}{'bezeichnung'});
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'farbe'});
   ${$rbuf} .= sprintf(" %-50.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf(" %02d",${$rtel}{'layout_nr'});
}


sub KAD_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KAD";
   ${$rbuf} .= sprintf("%-4.4s",${$rtel}{'auft_typ_kr'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'auftr_typ_arl'});
   ${$rbuf} .= sprintf("%02d",${$rtel}{'subtyp'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'auft_seq'});
   ${$rbuf} .= sprintf("%03d",${$rtel}{'tag'});
   ${$rbuf} .= sprintf("%01d",${$rtel}{'lv'});
   ${$rbuf} .= sprintf("%02d",${$rtel}{'batch'});
   ${$rbuf} .= sprintf("%01d",${$rtel}{'subbatch'});
   ${$rbuf} .= sprintf("%04d",${$rtel}{'sdg_im_batch'});
   ${$rbuf} .= sprintf("%02d",${$rtel}{'artikelzaehler'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'bs_flag'});
   ${$rbuf} .= sprintf("%-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("%-3.3s",${$rtel}{'artikelgrs'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("%07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("%-18.18s",${$rtel}{'bezeichnung'});
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'farbe'});
   ${$rbuf} .= sprintf("%-50.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf("%02d",${$rtel}{'layout_nr'});
}


sub KAD_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KAD";
   ${$rbuf} .= sprintf("\t%-.4s",${$rtel}{'auft_typ_kr'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'auftr_typ_arl'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'subtyp'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'auft_seq'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'tag'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'lv'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'batch'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'subbatch'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'sdg_im_batch'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'artikelzaehler'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'bs_flag'});
   ${$rbuf} .= sprintf("\t%-.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("\t%-.3s",${$rtel}{'artikelgrs'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("\t%-.18s",${$rtel}{'bezeichnung'});
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'farbe'});
   ${$rbuf} .= sprintf("\t%-.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'layout_nr'});
}


sub KAD_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KAD: ";
   $trcbuf .= "auft_typ_kr='" . substr(${$rbuf},4,4) . "', ";
   $trcbuf .= "auftr_typ_arl='" . substr(${$rbuf},9,1) . "', ";
   $trcbuf .= "subtyp=" . sprintf("%d",substr(${$rbuf},11,2)) . ", ";
   $trcbuf .= "auft_seq=" . sprintf("%d",substr(${$rbuf},14,6)) . ", ";
   $trcbuf .= "tag=" . sprintf("%d",substr(${$rbuf},21,3)) . ", ";
   $trcbuf .= "lv=" . sprintf("%d",substr(${$rbuf},25,1)) . ", ";
   $trcbuf .= "batch=" . sprintf("%d",substr(${$rbuf},27,2)) . ", ";
   $trcbuf .= "subbatch=" . sprintf("%d",substr(${$rbuf},30,1)) . ", ";
   $trcbuf .= "sdg_im_batch=" . sprintf("%d",substr(${$rbuf},32,4)) . ", ";
   $trcbuf .= "artikelzaehler=" . sprintf("%d",substr(${$rbuf},37,2)) . ", ";
   $trcbuf .= "bs_flag='" . substr(${$rbuf},40,1) . "', ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},42,14) . "', ";
   $trcbuf .= "artikelgrs='" . substr(${$rbuf},57,3) . "', ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},61,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},68,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},70,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},72,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},80,6)) . ", ";
   $trcbuf .= "bezeichnung='" . substr(${$rbuf},87,18) . "', ";
   $trcbuf .= "farbe='" . substr(${$rbuf},106,12) . "', ";
   $trcbuf .= "upi='" . substr(${$rbuf},119,50) . "', ";
   $trcbuf .= "layout_nr=" . sprintf("%d",substr(${$rbuf},170,2)) . "";

   return $trcbuf;
}


sub KAD_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KAD: ";
   $trcbuf .= "auft_typ_kr='" . substr(${$rbuf},3,4) . "', ";
   $trcbuf .= "auftr_typ_arl='" . substr(${$rbuf},7,1) . "', ";
   $trcbuf .= "subtyp=" . sprintf("%d",substr(${$rbuf},8,2)) . ", ";
   $trcbuf .= "auft_seq=" . sprintf("%d",substr(${$rbuf},10,6)) . ", ";
   $trcbuf .= "tag=" . sprintf("%d",substr(${$rbuf},16,3)) . ", ";
   $trcbuf .= "lv=" . sprintf("%d",substr(${$rbuf},19,1)) . ", ";
   $trcbuf .= "batch=" . sprintf("%d",substr(${$rbuf},20,2)) . ", ";
   $trcbuf .= "subbatch=" . sprintf("%d",substr(${$rbuf},22,1)) . ", ";
   $trcbuf .= "sdg_im_batch=" . sprintf("%d",substr(${$rbuf},23,4)) . ", ";
   $trcbuf .= "artikelzaehler=" . sprintf("%d",substr(${$rbuf},27,2)) . ", ";
   $trcbuf .= "bs_flag='" . substr(${$rbuf},29,1) . "', ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},30,14) . "', ";
   $trcbuf .= "artikelgrs='" . substr(${$rbuf},44,3) . "', ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},47,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},53,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},54,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},55,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},62,6)) . ", ";
   $trcbuf .= "bezeichnung='" . substr(${$rbuf},68,18) . "', ";
   $trcbuf .= "farbe='" . substr(${$rbuf},86,12) . "', ";
   $trcbuf .= "upi='" . substr(${$rbuf},98,50) . "', ";
   $trcbuf .= "layout_nr=" . sprintf("%d",substr(${$rbuf},148,2)) . "";

   return $trcbuf;
}


sub KAD_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KAD: ";
   $trcbuf .= "auft_typ_kr='" . $f[1]  . "', ";
   $trcbuf .= "auftr_typ_arl='" . $f[2]  . "', ";
   $trcbuf .= "subtyp=" . $f[3]  . ", ";
   $trcbuf .= "auft_seq=" . $f[4]  . ", ";
   $trcbuf .= "tag=" . $f[5]  . ", ";
   $trcbuf .= "lv=" . $f[6]  . ", ";
   $trcbuf .= "batch=" . $f[7]  . ", ";
   $trcbuf .= "subbatch=" . $f[8]  . ", ";
   $trcbuf .= "sdg_im_batch=" . $f[9]  . ", ";
   $trcbuf .= "artikelzaehler=" . $f[10]  . ", ";
   $trcbuf .= "bs_flag='" . $f[11]  . "', ";
   $trcbuf .= "artikelnr='" . $f[12]  . "', ";
   $trcbuf .= "artikelgrs='" . $f[13]  . "', ";
   $trcbuf .= "lkz=" . $f[14]  . ", ";
   $trcbuf .= "zoll_kz='" . $f[15]  . "', ";
   $trcbuf .= "sperr_kz='" . $f[16]  . "', ";
   $trcbuf .= "we_sendung=" . $f[17]  . ", ";
   $trcbuf .= "wap=" . $f[18]  . ", ";
   $trcbuf .= "bezeichnung='" . $f[19]  . "', ";
   $trcbuf .= "farbe='" . $f[20]  . "', ";
   $trcbuf .= "upi='" . $f[21]  . "', ";
   $trcbuf .= "layout_nr=" . $f[22]  . "";

   return $trcbuf;
}


sub KAD_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KAD: ";
   $trcbuf .= "auft_typ_kr='" . ${$rtel}{"auft_typ_kr"} . "', ";
   $trcbuf .= "auftr_typ_arl='" . ${$rtel}{"auftr_typ_arl"} . "', ";
   $trcbuf .= "subtyp=" . ${$rtel}{"subtyp"} . ", ";
   $trcbuf .= "auft_seq=" . ${$rtel}{"auft_seq"} . ", ";
   $trcbuf .= "tag=" . ${$rtel}{"tag"} . ", ";
   $trcbuf .= "lv=" . ${$rtel}{"lv"} . ", ";
   $trcbuf .= "batch=" . ${$rtel}{"batch"} . ", ";
   $trcbuf .= "subbatch=" . ${$rtel}{"subbatch"} . ", ";
   $trcbuf .= "sdg_im_batch=" . ${$rtel}{"sdg_im_batch"} . ", ";
   $trcbuf .= "artikelzaehler=" . ${$rtel}{"artikelzaehler"} . ", ";
   $trcbuf .= "bs_flag='" . ${$rtel}{"bs_flag"} . "', ";
   $trcbuf .= "artikelnr='" . ${$rtel}{"artikelnr"} . "', ";
   $trcbuf .= "artikelgrs='" . ${$rtel}{"artikelgrs"} . "', ";
   $trcbuf .= "lkz=" . ${$rtel}{"lkz"} . ", ";
   $trcbuf .= "zoll_kz='" . ${$rtel}{"zoll_kz"} . "', ";
   $trcbuf .= "sperr_kz='" . ${$rtel}{"sperr_kz"} . "', ";
   $trcbuf .= "we_sendung=" . ${$rtel}{"we_sendung"} . ", ";
   $trcbuf .= "wap=" . ${$rtel}{"wap"} . ", ";
   $trcbuf .= "bezeichnung='" . ${$rtel}{"bezeichnung"} . "', ";
   $trcbuf .= "farbe='" . ${$rtel}{"farbe"} . "', ";
   $trcbuf .= "upi='" . ${$rtel}{"upi"} . "', ";
   $trcbuf .= "layout_nr=" . ${$rtel}{"layout_nr"} . "";

   return $trcbuf;
}



#############################################################
#  Telegramm KAU                                            #
#############################################################

sub KAU_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KAU";
   ${$rtel}{'artikelnr'} = substr(${$rbuf},4,14);
   ${$rtel}{'artikelgrs'} = substr(${$rbuf},19,3);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},23,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},31,6));
   ${$rtel}{'zoll_kz_alt'} = substr(${$rbuf},38,1);
   ${$rtel}{'sperr_kz_alt'} = substr(${$rbuf},40,1);
   ${$rtel}{'zoll_kz_neu'} = substr(${$rbuf},42,1);
   ${$rtel}{'sperr_kz_neu'} = substr(${$rbuf},44,1);
   ${$rtel}{'mng_update'} = sprintf("%d",substr(${$rbuf},46,6));
}


sub KAU_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KAU";
   ${$rtel}{'artikelnr'} = substr(${$rbuf},3,14);
   ${$rtel}{'artikelgrs'} = substr(${$rbuf},17,3);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},20,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},27,6));
   ${$rtel}{'zoll_kz_alt'} = substr(${$rbuf},33,1);
   ${$rtel}{'sperr_kz_alt'} = substr(${$rbuf},34,1);
   ${$rtel}{'zoll_kz_neu'} = substr(${$rbuf},35,1);
   ${$rtel}{'sperr_kz_neu'} = substr(${$rbuf},36,1);
   ${$rtel}{'mng_update'} = sprintf("%d",substr(${$rbuf},37,6));
}


sub KAU_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KAU";
   ${$rtel}{'artikelnr'} = $f[1];
   ${$rtel}{'artikelgrs'} = $f[2];
   ${$rtel}{'we_sendung'} = sprintf("%d",$f[3]);
   ${$rtel}{'wap'} = sprintf("%d",$f[4]);
   ${$rtel}{'zoll_kz_alt'} = $f[5];
   ${$rtel}{'sperr_kz_alt'} = $f[6];
   ${$rtel}{'zoll_kz_neu'} = $f[7];
   ${$rtel}{'sperr_kz_neu'} = $f[8];
   ${$rtel}{'mng_update'} = sprintf("%d",$f[9]);
}


sub KAU_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KAU";
   ${$rbuf} .= sprintf(" %-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf(" %-3.3s",${$rtel}{'artikelgrs'});
   ${$rbuf} .= sprintf(" %07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'zoll_kz_alt'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'sperr_kz_alt'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'zoll_kz_neu'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'sperr_kz_neu'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'mng_update'});
}


sub KAU_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KAU";
   ${$rbuf} .= sprintf("%-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("%-3.3s",${$rtel}{'artikelgrs'});
   ${$rbuf} .= sprintf("%07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'zoll_kz_alt'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'sperr_kz_alt'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'zoll_kz_neu'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'sperr_kz_neu'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'mng_update'});
}


sub KAU_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KAU";
   ${$rbuf} .= sprintf("\t%-.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("\t%-.3s",${$rtel}{'artikelgrs'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'zoll_kz_alt'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'sperr_kz_alt'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'zoll_kz_neu'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'sperr_kz_neu'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'mng_update'});
}


sub KAU_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KAU: ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},4,14) . "', ";
   $trcbuf .= "artikelgrs='" . substr(${$rbuf},19,3) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},23,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},31,6)) . ", ";
   $trcbuf .= "zoll_kz_alt='" . substr(${$rbuf},38,1) . "', ";
   $trcbuf .= "sperr_kz_alt='" . substr(${$rbuf},40,1) . "', ";
   $trcbuf .= "zoll_kz_neu='" . substr(${$rbuf},42,1) . "', ";
   $trcbuf .= "sperr_kz_neu='" . substr(${$rbuf},44,1) . "', ";
   $trcbuf .= "mng_update=" . sprintf("%d",substr(${$rbuf},46,6)) . "";

   return $trcbuf;
}


sub KAU_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KAU: ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},3,14) . "', ";
   $trcbuf .= "artikelgrs='" . substr(${$rbuf},17,3) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},20,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},27,6)) . ", ";
   $trcbuf .= "zoll_kz_alt='" . substr(${$rbuf},33,1) . "', ";
   $trcbuf .= "sperr_kz_alt='" . substr(${$rbuf},34,1) . "', ";
   $trcbuf .= "zoll_kz_neu='" . substr(${$rbuf},35,1) . "', ";
   $trcbuf .= "sperr_kz_neu='" . substr(${$rbuf},36,1) . "', ";
   $trcbuf .= "mng_update=" . sprintf("%d",substr(${$rbuf},37,6)) . "";

   return $trcbuf;
}


sub KAU_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KAU: ";
   $trcbuf .= "artikelnr='" . $f[1]  . "', ";
   $trcbuf .= "artikelgrs='" . $f[2]  . "', ";
   $trcbuf .= "we_sendung=" . $f[3]  . ", ";
   $trcbuf .= "wap=" . $f[4]  . ", ";
   $trcbuf .= "zoll_kz_alt='" . $f[5]  . "', ";
   $trcbuf .= "sperr_kz_alt='" . $f[6]  . "', ";
   $trcbuf .= "zoll_kz_neu='" . $f[7]  . "', ";
   $trcbuf .= "sperr_kz_neu='" . $f[8]  . "', ";
   $trcbuf .= "mng_update=" . $f[9]  . "";

   return $trcbuf;
}


sub KAU_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KAU: ";
   $trcbuf .= "artikelnr='" . ${$rtel}{"artikelnr"} . "', ";
   $trcbuf .= "artikelgrs='" . ${$rtel}{"artikelgrs"} . "', ";
   $trcbuf .= "we_sendung=" . ${$rtel}{"we_sendung"} . ", ";
   $trcbuf .= "wap=" . ${$rtel}{"wap"} . ", ";
   $trcbuf .= "zoll_kz_alt='" . ${$rtel}{"zoll_kz_alt"} . "', ";
   $trcbuf .= "sperr_kz_alt='" . ${$rtel}{"sperr_kz_alt"} . "', ";
   $trcbuf .= "zoll_kz_neu='" . ${$rtel}{"zoll_kz_neu"} . "', ";
   $trcbuf .= "sperr_kz_neu='" . ${$rtel}{"sperr_kz_neu"} . "', ";
   $trcbuf .= "mng_update=" . ${$rtel}{"mng_update"} . "";

   return $trcbuf;
}



#############################################################
#  Telegramm LF2                                            #
#############################################################

sub LF2_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "LF2";
   ${$rtel}{'tag'} = sprintf("%d",substr(${$rbuf},4,3));
   ${$rtel}{'lv'} = sprintf("%d",substr(${$rbuf},8,1));
   ${$rtel}{'batch'} = sprintf("%d",substr(${$rbuf},10,2));
   ${$rtel}{'sdg_im_batch'} = sprintf("%d",substr(${$rbuf},13,4));
   ${$rtel}{'artikelzaehler'} = sprintf("%d",substr(${$rbuf},18,2));
   ${$rtel}{'auft_typ_kr'} = substr(${$rbuf},21,4);
   ${$rtel}{'auftragskategorie'} = substr(${$rbuf},26,1);
   ${$rtel}{'artikelnr'} = substr(${$rbuf},28,14);
   ${$rtel}{'groesse'} = substr(${$rbuf},43,3);
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},47,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},54,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},56,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},58,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},66,6));
   ${$rtel}{'ap'} = sprintf("%d",substr(${$rbuf},73,3));
   ${$rtel}{'wannen_id'} = substr(${$rbuf},77,10);
   ${$rtel}{'identcode'} = substr(${$rbuf},88,30);
}


sub LF2_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "LF2";
   ${$rtel}{'tag'} = sprintf("%d",substr(${$rbuf},3,3));
   ${$rtel}{'lv'} = sprintf("%d",substr(${$rbuf},6,1));
   ${$rtel}{'batch'} = sprintf("%d",substr(${$rbuf},7,2));
   ${$rtel}{'sdg_im_batch'} = sprintf("%d",substr(${$rbuf},9,4));
   ${$rtel}{'artikelzaehler'} = sprintf("%d",substr(${$rbuf},13,2));
   ${$rtel}{'auft_typ_kr'} = substr(${$rbuf},15,4);
   ${$rtel}{'auftragskategorie'} = substr(${$rbuf},19,1);
   ${$rtel}{'artikelnr'} = substr(${$rbuf},20,14);
   ${$rtel}{'groesse'} = substr(${$rbuf},34,3);
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},37,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},43,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},44,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},45,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},52,6));
   ${$rtel}{'ap'} = sprintf("%d",substr(${$rbuf},58,3));
   ${$rtel}{'wannen_id'} = substr(${$rbuf},61,10);
   ${$rtel}{'identcode'} = substr(${$rbuf},71,30);
}


sub LF2_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "LF2";
   ${$rtel}{'tag'} = sprintf("%d",$f[1]);
   ${$rtel}{'lv'} = sprintf("%d",$f[2]);
   ${$rtel}{'batch'} = sprintf("%d",$f[3]);
   ${$rtel}{'sdg_im_batch'} = sprintf("%d",$f[4]);
   ${$rtel}{'artikelzaehler'} = sprintf("%d",$f[5]);
   ${$rtel}{'auft_typ_kr'} = $f[6];
   ${$rtel}{'auftragskategorie'} = $f[7];
   ${$rtel}{'artikelnr'} = $f[8];
   ${$rtel}{'groesse'} = $f[9];
   ${$rtel}{'lkz'} = sprintf("%d",$f[10]);
   ${$rtel}{'zoll_kz'} = $f[11];
   ${$rtel}{'sperr_kz'} = $f[12];
   ${$rtel}{'we_sendung'} = sprintf("%d",$f[13]);
   ${$rtel}{'wap'} = sprintf("%d",$f[14]);
   ${$rtel}{'ap'} = sprintf("%d",$f[15]);
   ${$rtel}{'wannen_id'} = $f[16];
   ${$rtel}{'identcode'} = $f[17];
}


sub LF2_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "LF2";
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'tag'});
   ${$rbuf} .= sprintf(" %01d",${$rtel}{'lv'});
   ${$rbuf} .= sprintf(" %02d",${$rtel}{'batch'});
   ${$rbuf} .= sprintf(" %04d",${$rtel}{'sdg_im_batch'});
   ${$rbuf} .= sprintf(" %02d",${$rtel}{'artikelzaehler'});
   ${$rbuf} .= sprintf(" %-4.4s",${$rtel}{'auft_typ_kr'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'auftragskategorie'});
   ${$rbuf} .= sprintf(" %-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf(" %-3.3s",${$rtel}{'groesse'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf(" %07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'ap'});
   ${$rbuf} .= sprintf(" %-10.10s",${$rtel}{'wannen_id'});
   ${$rbuf} .= sprintf(" %-30.30s",${$rtel}{'identcode'});
}


sub LF2_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "LF2";
   ${$rbuf} .= sprintf("%03d",${$rtel}{'tag'});
   ${$rbuf} .= sprintf("%01d",${$rtel}{'lv'});
   ${$rbuf} .= sprintf("%02d",${$rtel}{'batch'});
   ${$rbuf} .= sprintf("%04d",${$rtel}{'sdg_im_batch'});
   ${$rbuf} .= sprintf("%02d",${$rtel}{'artikelzaehler'});
   ${$rbuf} .= sprintf("%-4.4s",${$rtel}{'auft_typ_kr'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'auftragskategorie'});
   ${$rbuf} .= sprintf("%-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("%-3.3s",${$rtel}{'groesse'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("%07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("%03d",${$rtel}{'ap'});
   ${$rbuf} .= sprintf("%-10.10s",${$rtel}{'wannen_id'});
   ${$rbuf} .= sprintf("%-30.30s",${$rtel}{'identcode'});
}


sub LF2_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "LF2";
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'tag'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'lv'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'batch'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'sdg_im_batch'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'artikelzaehler'});
   ${$rbuf} .= sprintf("\t%-.4s",${$rtel}{'auft_typ_kr'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'auftragskategorie'});
   ${$rbuf} .= sprintf("\t%-.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("\t%-.3s",${$rtel}{'groesse'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'ap'});
   ${$rbuf} .= sprintf("\t%-.10s",${$rtel}{'wannen_id'});
   ${$rbuf} .= sprintf("\t%-.30s",${$rtel}{'identcode'});
}


sub LF2_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm LF2: ";
   $trcbuf .= "tag=" . sprintf("%d",substr(${$rbuf},4,3)) . ", ";
   $trcbuf .= "lv=" . sprintf("%d",substr(${$rbuf},8,1)) . ", ";
   $trcbuf .= "batch=" . sprintf("%d",substr(${$rbuf},10,2)) . ", ";
   $trcbuf .= "sdg_im_batch=" . sprintf("%d",substr(${$rbuf},13,4)) . ", ";
   $trcbuf .= "artikelzaehler=" . sprintf("%d",substr(${$rbuf},18,2)) . ", ";
   $trcbuf .= "auft_typ_kr='" . substr(${$rbuf},21,4) . "', ";
   $trcbuf .= "auftragskategorie='" . substr(${$rbuf},26,1) . "', ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},28,14) . "', ";
   $trcbuf .= "groesse='" . substr(${$rbuf},43,3) . "', ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},47,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},54,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},56,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},58,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},66,6)) . ", ";
   $trcbuf .= "ap=" . sprintf("%d",substr(${$rbuf},73,3)) . ", ";
   $trcbuf .= "wannen_id='" . substr(${$rbuf},77,10) . "', ";
   $trcbuf .= "identcode='" . substr(${$rbuf},88,30) . "'";

   return $trcbuf;
}


sub LF2_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm LF2: ";
   $trcbuf .= "tag=" . sprintf("%d",substr(${$rbuf},3,3)) . ", ";
   $trcbuf .= "lv=" . sprintf("%d",substr(${$rbuf},6,1)) . ", ";
   $trcbuf .= "batch=" . sprintf("%d",substr(${$rbuf},7,2)) . ", ";
   $trcbuf .= "sdg_im_batch=" . sprintf("%d",substr(${$rbuf},9,4)) . ", ";
   $trcbuf .= "artikelzaehler=" . sprintf("%d",substr(${$rbuf},13,2)) . ", ";
   $trcbuf .= "auft_typ_kr='" . substr(${$rbuf},15,4) . "', ";
   $trcbuf .= "auftragskategorie='" . substr(${$rbuf},19,1) . "', ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},20,14) . "', ";
   $trcbuf .= "groesse='" . substr(${$rbuf},34,3) . "', ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},37,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},43,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},44,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},45,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},52,6)) . ", ";
   $trcbuf .= "ap=" . sprintf("%d",substr(${$rbuf},58,3)) . ", ";
   $trcbuf .= "wannen_id='" . substr(${$rbuf},61,10) . "', ";
   $trcbuf .= "identcode='" . substr(${$rbuf},71,30) . "'";

   return $trcbuf;
}


sub LF2_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm LF2: ";
   $trcbuf .= "tag=" . $f[1]  . ", ";
   $trcbuf .= "lv=" . $f[2]  . ", ";
   $trcbuf .= "batch=" . $f[3]  . ", ";
   $trcbuf .= "sdg_im_batch=" . $f[4]  . ", ";
   $trcbuf .= "artikelzaehler=" . $f[5]  . ", ";
   $trcbuf .= "auft_typ_kr='" . $f[6]  . "', ";
   $trcbuf .= "auftragskategorie='" . $f[7]  . "', ";
   $trcbuf .= "artikelnr='" . $f[8]  . "', ";
   $trcbuf .= "groesse='" . $f[9]  . "', ";
   $trcbuf .= "lkz=" . $f[10]  . ", ";
   $trcbuf .= "zoll_kz='" . $f[11]  . "', ";
   $trcbuf .= "sperr_kz='" . $f[12]  . "', ";
   $trcbuf .= "we_sendung=" . $f[13]  . ", ";
   $trcbuf .= "wap=" . $f[14]  . ", ";
   $trcbuf .= "ap=" . $f[15]  . ", ";
   $trcbuf .= "wannen_id='" . $f[16]  . "', ";
   $trcbuf .= "identcode='" . $f[17]  . "'";

   return $trcbuf;
}


sub LF2_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm LF2: ";
   $trcbuf .= "tag=" . ${$rtel}{"tag"} . ", ";
   $trcbuf .= "lv=" . ${$rtel}{"lv"} . ", ";
   $trcbuf .= "batch=" . ${$rtel}{"batch"} . ", ";
   $trcbuf .= "sdg_im_batch=" . ${$rtel}{"sdg_im_batch"} . ", ";
   $trcbuf .= "artikelzaehler=" . ${$rtel}{"artikelzaehler"} . ", ";
   $trcbuf .= "auft_typ_kr='" . ${$rtel}{"auft_typ_kr"} . "', ";
   $trcbuf .= "auftragskategorie='" . ${$rtel}{"auftragskategorie"} . "', ";
   $trcbuf .= "artikelnr='" . ${$rtel}{"artikelnr"} . "', ";
   $trcbuf .= "groesse='" . ${$rtel}{"groesse"} . "', ";
   $trcbuf .= "lkz=" . ${$rtel}{"lkz"} . ", ";
   $trcbuf .= "zoll_kz='" . ${$rtel}{"zoll_kz"} . "', ";
   $trcbuf .= "sperr_kz='" . ${$rtel}{"sperr_kz"} . "', ";
   $trcbuf .= "we_sendung=" . ${$rtel}{"we_sendung"} . ", ";
   $trcbuf .= "wap=" . ${$rtel}{"wap"} . ", ";
   $trcbuf .= "ap=" . ${$rtel}{"ap"} . ", ";
   $trcbuf .= "wannen_id='" . ${$rtel}{"wannen_id"} . "', ";
   $trcbuf .= "identcode='" . ${$rtel}{"identcode"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm KBA                                            #
#############################################################

sub KBA_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KBA";
   ${$rtel}{'anfrage_typ'} = substr(${$rbuf},4,1);
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},6,12);
}


sub KBA_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KBA";
   ${$rtel}{'anfrage_typ'} = substr(${$rbuf},3,1);
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},4,12);
}


sub KBA_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KBA";
   ${$rtel}{'anfrage_typ'} = $f[1];
   ${$rtel}{'wannen_id_12'} = $f[2];
}


sub KBA_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KBA";
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'anfrage_typ'});
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'wannen_id_12'});
}


sub KBA_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KBA";
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'anfrage_typ'});
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'wannen_id_12'});
}


sub KBA_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KBA";
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'anfrage_typ'});
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'wannen_id_12'});
}


sub KBA_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KBA: ";
   $trcbuf .= "anfrage_typ='" . substr(${$rbuf},4,1) . "', ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},6,12) . "'";

   return $trcbuf;
}


sub KBA_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KBA: ";
   $trcbuf .= "anfrage_typ='" . substr(${$rbuf},3,1) . "', ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},4,12) . "'";

   return $trcbuf;
}


sub KBA_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KBA: ";
   $trcbuf .= "anfrage_typ='" . $f[1]  . "', ";
   $trcbuf .= "wannen_id_12='" . $f[2]  . "'";

   return $trcbuf;
}


sub KBA_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KBA: ";
   $trcbuf .= "anfrage_typ='" . ${$rtel}{"anfrage_typ"} . "', ";
   $trcbuf .= "wannen_id_12='" . ${$rtel}{"wannen_id_12"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm KB1                                            #
#############################################################

sub KB1_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KB1";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},4,12);
   ${$rtel}{'gasse'} = sprintf("%d",substr(${$rbuf},17,2));
   ${$rtel}{'x_koord'} = sprintf("%d",substr(${$rbuf},20,3));
   ${$rtel}{'y_koord'} = sprintf("%d",substr(${$rbuf},24,3));
   ${$rtel}{'z_koord'} = sprintf("%d",substr(${$rbuf},28,3));
   ${$rtel}{'artikelnr'} = substr(${$rbuf},32,14);
   ${$rtel}{'grs'} = sprintf("%d",substr(${$rbuf},47,3));
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},51,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},58,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},60,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},62,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},70,6));
   ${$rtel}{'upi'} = substr(${$rbuf},77,50);
   ${$rtel}{'menge'} = sprintf("%d",substr(${$rbuf},128,6));
   ${$rtel}{'last_flag'} = substr(${$rbuf},135,1);
}


sub KB1_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KB1";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},3,12);
   ${$rtel}{'gasse'} = sprintf("%d",substr(${$rbuf},15,2));
   ${$rtel}{'x_koord'} = sprintf("%d",substr(${$rbuf},17,3));
   ${$rtel}{'y_koord'} = sprintf("%d",substr(${$rbuf},20,3));
   ${$rtel}{'z_koord'} = sprintf("%d",substr(${$rbuf},23,3));
   ${$rtel}{'artikelnr'} = substr(${$rbuf},26,14);
   ${$rtel}{'grs'} = sprintf("%d",substr(${$rbuf},40,3));
   ${$rtel}{'lkz'} = sprintf("%d",substr(${$rbuf},43,6));
   ${$rtel}{'zoll_kz'} = substr(${$rbuf},49,1);
   ${$rtel}{'sperr_kz'} = substr(${$rbuf},50,1);
   ${$rtel}{'we_sendung'} = sprintf("%d",substr(${$rbuf},51,7));
   ${$rtel}{'wap'} = sprintf("%d",substr(${$rbuf},58,6));
   ${$rtel}{'upi'} = substr(${$rbuf},64,50);
   ${$rtel}{'menge'} = sprintf("%d",substr(${$rbuf},114,6));
   ${$rtel}{'last_flag'} = substr(${$rbuf},120,1);
}


sub KB1_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KB1";
   ${$rtel}{'wannen_id_12'} = $f[1];
   ${$rtel}{'gasse'} = sprintf("%d",$f[2]);
   ${$rtel}{'x_koord'} = sprintf("%d",$f[3]);
   ${$rtel}{'y_koord'} = sprintf("%d",$f[4]);
   ${$rtel}{'z_koord'} = sprintf("%d",$f[5]);
   ${$rtel}{'artikelnr'} = $f[6];
   ${$rtel}{'grs'} = sprintf("%d",$f[7]);
   ${$rtel}{'lkz'} = sprintf("%d",$f[8]);
   ${$rtel}{'zoll_kz'} = $f[9];
   ${$rtel}{'sperr_kz'} = $f[10];
   ${$rtel}{'we_sendung'} = sprintf("%d",$f[11]);
   ${$rtel}{'wap'} = sprintf("%d",$f[12]);
   ${$rtel}{'upi'} = $f[13];
   ${$rtel}{'menge'} = sprintf("%d",$f[14]);
   ${$rtel}{'last_flag'} = $f[15];
}


sub KB1_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KB1";
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf(" %02d",${$rtel}{'gasse'});
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'x_koord'});
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'y_koord'});
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'z_koord'});
   ${$rbuf} .= sprintf(" %-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf(" %03d",${$rtel}{'grs'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf(" %07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf(" %-50.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'menge'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'last_flag'});
}


sub KB1_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KB1";
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("%02d",${$rtel}{'gasse'});
   ${$rbuf} .= sprintf("%03d",${$rtel}{'x_koord'});
   ${$rbuf} .= sprintf("%03d",${$rtel}{'y_koord'});
   ${$rbuf} .= sprintf("%03d",${$rtel}{'z_koord'});
   ${$rbuf} .= sprintf("%-14.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("%03d",${$rtel}{'grs'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("%07d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("%-50.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf("%06d",${$rtel}{'menge'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'last_flag'});
}


sub KB1_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KB1";
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'gasse'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'x_koord'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'y_koord'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'z_koord'});
   ${$rbuf} .= sprintf("\t%-.14s",${$rtel}{'artikelnr'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'grs'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'lkz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'zoll_kz'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'sperr_kz'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'we_sendung'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'wap'});
   ${$rbuf} .= sprintf("\t%-.50s",${$rtel}{'upi'});
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'menge'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'last_flag'});
}


sub KB1_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KB1: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},4,12) . "', ";
   $trcbuf .= "gasse=" . sprintf("%d",substr(${$rbuf},17,2)) . ", ";
   $trcbuf .= "x_koord=" . sprintf("%d",substr(${$rbuf},20,3)) . ", ";
   $trcbuf .= "y_koord=" . sprintf("%d",substr(${$rbuf},24,3)) . ", ";
   $trcbuf .= "z_koord=" . sprintf("%d",substr(${$rbuf},28,3)) . ", ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},32,14) . "', ";
   $trcbuf .= "grs=" . sprintf("%d",substr(${$rbuf},47,3)) . ", ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},51,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},58,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},60,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},62,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},70,6)) . ", ";
   $trcbuf .= "upi='" . substr(${$rbuf},77,50) . "', ";
   $trcbuf .= "menge=" . sprintf("%d",substr(${$rbuf},128,6)) . ", ";
   $trcbuf .= "last_flag='" . substr(${$rbuf},135,1) . "'";

   return $trcbuf;
}


sub KB1_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KB1: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},3,12) . "', ";
   $trcbuf .= "gasse=" . sprintf("%d",substr(${$rbuf},15,2)) . ", ";
   $trcbuf .= "x_koord=" . sprintf("%d",substr(${$rbuf},17,3)) . ", ";
   $trcbuf .= "y_koord=" . sprintf("%d",substr(${$rbuf},20,3)) . ", ";
   $trcbuf .= "z_koord=" . sprintf("%d",substr(${$rbuf},23,3)) . ", ";
   $trcbuf .= "artikelnr='" . substr(${$rbuf},26,14) . "', ";
   $trcbuf .= "grs=" . sprintf("%d",substr(${$rbuf},40,3)) . ", ";
   $trcbuf .= "lkz=" . sprintf("%d",substr(${$rbuf},43,6)) . ", ";
   $trcbuf .= "zoll_kz='" . substr(${$rbuf},49,1) . "', ";
   $trcbuf .= "sperr_kz='" . substr(${$rbuf},50,1) . "', ";
   $trcbuf .= "we_sendung=" . sprintf("%d",substr(${$rbuf},51,7)) . ", ";
   $trcbuf .= "wap=" . sprintf("%d",substr(${$rbuf},58,6)) . ", ";
   $trcbuf .= "upi='" . substr(${$rbuf},64,50) . "', ";
   $trcbuf .= "menge=" . sprintf("%d",substr(${$rbuf},114,6)) . ", ";
   $trcbuf .= "last_flag='" . substr(${$rbuf},120,1) . "'";

   return $trcbuf;
}


sub KB1_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KB1: ";
   $trcbuf .= "wannen_id_12='" . $f[1]  . "', ";
   $trcbuf .= "gasse=" . $f[2]  . ", ";
   $trcbuf .= "x_koord=" . $f[3]  . ", ";
   $trcbuf .= "y_koord=" . $f[4]  . ", ";
   $trcbuf .= "z_koord=" . $f[5]  . ", ";
   $trcbuf .= "artikelnr='" . $f[6]  . "', ";
   $trcbuf .= "grs=" . $f[7]  . ", ";
   $trcbuf .= "lkz=" . $f[8]  . ", ";
   $trcbuf .= "zoll_kz='" . $f[9]  . "', ";
   $trcbuf .= "sperr_kz='" . $f[10]  . "', ";
   $trcbuf .= "we_sendung=" . $f[11]  . ", ";
   $trcbuf .= "wap=" . $f[12]  . ", ";
   $trcbuf .= "upi='" . $f[13]  . "', ";
   $trcbuf .= "menge=" . $f[14]  . ", ";
   $trcbuf .= "last_flag='" . $f[15]  . "'";

   return $trcbuf;
}


sub KB1_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KB1: ";
   $trcbuf .= "wannen_id_12='" . ${$rtel}{"wannen_id_12"} . "', ";
   $trcbuf .= "gasse=" . ${$rtel}{"gasse"} . ", ";
   $trcbuf .= "x_koord=" . ${$rtel}{"x_koord"} . ", ";
   $trcbuf .= "y_koord=" . ${$rtel}{"y_koord"} . ", ";
   $trcbuf .= "z_koord=" . ${$rtel}{"z_koord"} . ", ";
   $trcbuf .= "artikelnr='" . ${$rtel}{"artikelnr"} . "', ";
   $trcbuf .= "grs=" . ${$rtel}{"grs"} . ", ";
   $trcbuf .= "lkz=" . ${$rtel}{"lkz"} . ", ";
   $trcbuf .= "zoll_kz='" . ${$rtel}{"zoll_kz"} . "', ";
   $trcbuf .= "sperr_kz='" . ${$rtel}{"sperr_kz"} . "', ";
   $trcbuf .= "we_sendung=" . ${$rtel}{"we_sendung"} . ", ";
   $trcbuf .= "wap=" . ${$rtel}{"wap"} . ", ";
   $trcbuf .= "upi='" . ${$rtel}{"upi"} . "', ";
   $trcbuf .= "menge=" . ${$rtel}{"menge"} . ", ";
   $trcbuf .= "last_flag='" . ${$rtel}{"last_flag"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm KB2                                            #
#############################################################

sub KB2_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KB2";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},4,12);
   ${$rtel}{'last_flag'} = substr(${$rbuf},17,1);
}


sub KB2_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "KB2";
   ${$rtel}{'wannen_id_12'} = substr(${$rbuf},3,12);
   ${$rtel}{'last_flag'} = substr(${$rbuf},15,1);
}


sub KB2_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "KB2";
   ${$rtel}{'wannen_id_12'} = $f[1];
   ${$rtel}{'last_flag'} = $f[2];
}


sub KB2_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KB2";
   ${$rbuf} .= sprintf(" %-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'last_flag'});
}


sub KB2_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KB2";
   ${$rbuf} .= sprintf("%-12.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'last_flag'});
}


sub KB2_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "KB2";
   ${$rbuf} .= sprintf("\t%-.12s",${$rtel}{'wannen_id_12'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'last_flag'});
}


sub KB2_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KB2: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},4,12) . "', ";
   $trcbuf .= "last_flag='" . substr(${$rbuf},17,1) . "'";

   return $trcbuf;
}


sub KB2_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KB2: ";
   $trcbuf .= "wannen_id_12='" . substr(${$rbuf},3,12) . "', ";
   $trcbuf .= "last_flag='" . substr(${$rbuf},15,1) . "'";

   return $trcbuf;
}


sub KB2_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm KB2: ";
   $trcbuf .= "wannen_id_12='" . $f[1]  . "', ";
   $trcbuf .= "last_flag='" . $f[2]  . "'";

   return $trcbuf;
}


sub KB2_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm KB2: ";
   $trcbuf .= "wannen_id_12='" . ${$rtel}{"wannen_id_12"} . "', ";
   $trcbuf .= "last_flag='" . ${$rtel}{"last_flag"} . "'";

   return $trcbuf;
}



#############################################################
#  Telegramm PRNA                                           #
#############################################################

sub PRNA_buf_to_tel {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "PRNA";
   ${$rtel}{'druck_abruf_id'} = sprintf("%d",substr(${$rbuf},5,6));
   ${$rtel}{'etage'} = substr(${$rbuf},12,1);
   ${$rtel}{'druck_status'} = substr(${$rbuf},14,1);
}


sub PRNA_buf_to_tel_n {
   my ($rbuf,$rtel) = @_;

   ${$rtel}{'TELTYP'} = "PRNA";
   ${$rtel}{'druck_abruf_id'} = sprintf("%d",substr(${$rbuf},4,6));
   ${$rtel}{'etage'} = substr(${$rbuf},10,1);
   ${$rtel}{'druck_status'} = substr(${$rbuf},11,1);
}


sub PRNA_buf_to_tel_t {
   my ($rbuf,$rtel) = @_;

   my @f = split(/\t/,${$rbuf});

   ${$rtel}{'TELTYP'} = "PRNA";
   ${$rtel}{'druck_abruf_id'} = sprintf("%d",$f[1]);
   ${$rtel}{'etage'} = $f[2];
   ${$rtel}{'druck_status'} = $f[3];
}


sub PRNA_tel_to_buf {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "PRNA";
   ${$rbuf} .= sprintf(" %06d",${$rtel}{'druck_abruf_id'});
   ${$rbuf} .= sprintf(" %-1.1s",${$rtel}{'etage'});
   ${$rbuf} .= sprintf(" %s",${$rtel}{'druck_status'});
}


sub PRNA_tel_to_buf_n {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "PRNA";
   ${$rbuf} .= sprintf("%06d",${$rtel}{'druck_abruf_id'});
   ${$rbuf} .= sprintf("%-1.1s",${$rtel}{'etage'});
   ${$rbuf} .= sprintf("%s",${$rtel}{'druck_status'});
}


sub PRNA_tel_to_buf_t {
   my ($rtel,$rbuf) = @_;

   ${$rbuf}  = "PRNA";
   ${$rbuf} .= sprintf("\t%d",${$rtel}{'druck_abruf_id'});
   ${$rbuf} .= sprintf("\t%-.1s",${$rtel}{'etage'});
   ${$rbuf} .= sprintf("\t%s",${$rtel}{'druck_status'});
}


sub PRNA_trace_buf {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm PRNA: ";
   $trcbuf .= "druck_abruf_id=" . sprintf("%d",substr(${$rbuf},5,6)) . ", ";
   $trcbuf .= "etage='" . substr(${$rbuf},12,1) . "', ";
   $trcbuf .= "druck_status='" . substr(${$rbuf},14,1) . "'";

   return $trcbuf;
}


sub PRNA_trace_buf_n {
   my $rbuf = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm PRNA: ";
   $trcbuf .= "druck_abruf_id=" . sprintf("%d",substr(${$rbuf},4,6)) . ", ";
   $trcbuf .= "etage='" . substr(${$rbuf},10,1) . "', ";
   $trcbuf .= "druck_status='" . substr(${$rbuf},11,1) . "'";

   return $trcbuf;
}


sub PRNA_trace_buf_t {
   my $rbuf = shift;
   my $trcbuf;

   my @f = split(/\t/,${$rbuf});

   $trcbuf  = "Telegramm PRNA: ";
   $trcbuf .= "druck_abruf_id=" . $f[1]  . ", ";
   $trcbuf .= "etage='" . $f[2]  . "', ";
   $trcbuf .= "druck_status='" . $f[3]  . "'";

   return $trcbuf;
}


sub PRNA_trace_tel {
   my $rtel = shift;
   my $trcbuf;

   $trcbuf  = "Telegramm PRNA: ";
   $trcbuf .= "druck_abruf_id=" . ${$rtel}{"druck_abruf_id"} . ", ";
   $trcbuf .= "etage='" . ${$rtel}{"etage"} . "', ";
   $trcbuf .= "druck_status='" . ${$rtel}{"druck_status"} . "'";

   return $trcbuf;
}

1;
